from enum import Enum

PREFIX = 'BANGUMI_'

class Env(Enum):
    CLIENT_TYPE = PREFIX + 'CLIENT_TYPE'
    CLIENT_IP = PREFIX + 'CLIENT_IP'
    CLIENT_PORT = PREFIX + 'CLIENT_PORT'
    CLIENT_USERNAME = PREFIX + 'CLIENT_USERNAME'
    CLIENT_PASSWORD = PREFIX + 'CLIENT_PASSWORD'
    CACHE_FOLDER = PREFIX + 'CACHE_FOLDER'
    MEDIA_FOLDER = PREFIX + 'MEDIA_FOLDER'

    REDIS_HOST = PREFIX + 'REDIS_HOST'
    REDIS_PORT = PREFIX + 'REDIS_PORT'
    REDIS_PASSWORD = PREFIX + 'REDIS_PASSWORD'

    CHECK_INTERVAL = PREFIX + 'CHECK_INTERVAL'

    LOGGER_LEVEL = PREFIX + 'LOGGER_LEVEL'